# Numpy

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]
np.array(l, np.int8)

array([1, 2, 3, 4, 5], dtype=int8)

In [3]:
print(np.array(l))

[1 2 3 4 5]


In [4]:
A = np.array(l, np.int8)
print(A[2])

3


In [5]:
print(np.array([[1,2,3,4,5],[6,7,8,9,10]]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
print(np.array([[1,2,3,4,5],[6,7,8,9,10]])[0,1])

2


In [7]:
B = np.array([[1,2,3,4,5],[6,7,8,9,10]])
B.shape

(2, 5)

In [8]:
B.dtype

dtype('int64')

In [9]:
B[0,1] = 20

In [10]:
print(B)

[[ 1 20  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
zeroes = np.zeros((2,6))
zeroes

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
type(rng)

numpy.ndarray

In [14]:
rng.shape

(15,)

In [15]:
rng.size

15

In [16]:
lnspc = np.linspace(1, 3, 10)
lnspc

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [17]:
emp = np.empty((2,3))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.60219306e-306, 1.89146896e-307, 7.56571288e-307]])

In [18]:
emp_like = np.empty_like(lnspc)
emp_like

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [19]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
ide.shape

(5, 5)

In [21]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
C.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
C.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
C = C.reshape(5, 2)

In [26]:
C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
C = C.ravel()
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
C.shape

(10,)

In [29]:
D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
D.sum(axis = 0)

array([ 7,  9, 11, 13, 15])

In [31]:
D.sum(axis = 1)

array([15, 40])

In [32]:
D.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [33]:
D.flat

In [34]:
for i in D.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [35]:
D.size

10

In [36]:
D.nbytes

80

In [37]:
D.argmax()

np.int64(9)

In [38]:
print(D.argmin())

0


In [39]:
D.argsort(axis = 0)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [40]:
D.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
D.reshape((10,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
D.reshape((1,10))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [43]:
D.reshape((10, 1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [44]:
arr1 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
arr2 = np.array([[1,2,3,4,5,7], [7,8,9,10,11,13]])

In [45]:
arr1 + arr2

array([[ 2,  4,  6,  8, 10, 13],
       [14, 16, 18, 20, 22, 25]])

In [46]:
arr1 - arr2

array([[ 0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0, -1]])

In [47]:
arr1 * arr2

array([[  1,   4,   9,  16,  25,  42],
       [ 49,  64,  81, 100, 121, 156]])

In [48]:
arr1 / arr2

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        0.85714286],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.92307692]])

In [49]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162]])

In [50]:
print(np.max(arr1))

12


In [51]:
print(np.min(arr1))

1


In [52]:
np.count_nonzero(arr1)

np.int64(12)